### ISSUE TITLE
Can’t create symlinks

### ISSUE THREAD

**Issue by bob1321** [sirrobot01/debrid-blackhole#12]
Hello, the blackhole is not creating symlinks for Alldebrid when the files is directly in the magnets folder.
This is the log: [alldebrid] 2025/01/01 19:59:12 Torrent: The.Man.From.Rome.2022.MULTi.1080p.WEB-DL.H264-Slay3R.mkv downloaded
[QBit] 2025/01/01 19:59:12 Checking 1 files...

When the file is in a subfolder its working without problems.

If the file is in a second subfolder its not working.
This is the other log: [alldebrid] 2025/01/01 20:31:10 Torrent: Marvels.Iron.Fist.S01.MULTi.1080p.WEBRip.x264-BRiNK downloaded
[QBit] 2025/01/01 20:31:10 Checking 0 files...

**Comment by sirrobot01** [comment]
This should be fixed now in the new beta image

**Comment by vpierre1776** [comment]
> This should be fixed now in the new beta image. Logs looking this. Is there anything I should look at?

Pulled the ":beta" image, but still getting stuck at "checking files". Pretty sure permissions are good `2025/01/15 07:48:48 Error checking availability: {"success":false,"error":"unknowR","error_description":"Endpoint not found."}
status code: 404
[QBit] 2025/01/15 07:48:49 isSymlink: true
[torbox] 2025/01/15 07:48:49 Torrent Hash: 109ECFB0E68BC5DFF30AFD02495080744BC426D1
2025/01/15 07:48:49 Processing debrid:  torbox
2025/01/15 07:48:50 Processing debrid:  realdebrid
[torbox] 2025/01/15 07:48:50 Torrent: Free Guy 2021 2160p WEB-DL x265 10bit SDR DTS-HD MA 7 1-NOGRP is not cached
[realdebrid] 2025/01/15 07:48:50 Torrent Hash: 109ECFB0E68BC5DFF30AFD02495080744BC426D1
[realdebrid] 2025/01/15 07:48:50 Torrent: Free Guy 2021 2160p WEB-DL x265 10bit SDR DTS-HD MA 7 1-NOGRP is not cached
2025/01/15 07:48:50 Error checking availability: {
	"error": "disabled_endpoint",
	"error_code": 37
}
status code: 403
2025/01/15 07:48:50 Processing debrid:  debridlink
[debridlink] 2025/01/15 07:48:50 Torrent Hash: 109ECFB0E68BC5DFF30AFD02495080744BC426D1
2025/01/15 07:48:50 Error checking availability: {"success":false,"error":"unknowR","error_description":"Endpoint not found."}
status code: 404
[debridlink] 2025/01/15 07:48:50 Torrent: Free Guy 2021 2160p WEB-DL x265 10bit SDR DTS-HD MA 7 1-NOGRP is not cached
[QBit] 2025/01/15 07:48:50 Error adding magnet: failed to process torrent: failed to process torrent
2025/01/15 07:48:51 Processing debrid:  torbox
[QBit] 2025/01/15 07:48:51 isSymlink: true
[torbox] 2025/01/15 07:48:51 Torrent Hash: 45B15893AF962B6DD7FA6CE9CECBD5C424265F1B
[torbox] 2025/01/15 07:48:52 Torrent: Free Guy 2021 4K HDR 2160p WEBDL Ita Eng x265-NAHOM mkv is not cached
[realdebrid] 2025/01/15 07:48:52 Torrent Hash: 45B15893AF962B6DD7FA6CE9CECBD5C424265F1B
2025/01/15 07:48:52 Processing debrid:  realdebrid
[realdebrid] 2025/01/15 07:48:52 Torrent: Free Guy 2021 4K HDR 2160p WEBDL Ita Eng x265-NAHOM mkv is not cached
[debridlink] 2025/01/15 07:48:52 Torrent Hash: 45B15893AF962B6DD7FA6CE9CECBD5C424265F1B
2025/01/15 07:48:52 Error checking availability: {
	"error": "disabled_endpoint",
	"error_code": 37
}
status code: 403
2025/01/15 07:48:52 Processing debrid:  debridlink
[debridlink] 2025/01/15 07:48:52 Torrent: Free Guy 2021 4K HDR 2160p WEBDL Ita Eng x265-NAHOM mkv is not cached
[QBit] 2025/01/15 07:48:52 Error adding magnet: failed to process torrent: failed to process torrent
2025/01/15 07:48:52 Error checking availability: {"success":false,"error":"unknowR","error_description":"Endpoint not found."}
status code: 404
[QBit] 2025/01/15 07:48:53 isSymlink: true
[torbox] 2025/01/15 07:48:53 Torrent Hash: A5B994C80AFC344E28EFAD1C1EC693044BC6AB77
2025/01/15 07:48:53 Processing debrid:  torbox
2025/01/15 07:48:54 Processing debrid:  realdebrid
[torbox] 2025/01/15 07:48:54 Torrent: Free Guy 2021 2160p WEB-DL DDP5 1 Atmos DV MP4 x265-FLUX is not cached
[realdebrid] 2025/01/15 07:48:54 Torrent Hash: A5B994C80AFC344E28EFAD1C1EC693044BC6AB77
[realdebrid] 2025/01/15 07:48:54 Torrent: Free Guy 2021 2160p WEB-DL DDP5 1 Atmos DV MP4 x265-FLUX is not cached
[debridlink] 2025/01/15 07:48:54 Torrent Hash: A5B994C80AFC344E28EFAD1C1EC693044BC6AB77
2025/01/15 07:48:54 Error checking availability: {
	"error": "disabled_endpoint",
	"error_code": 37
}
status code: 403
2025/01/15 07:48:54 Processing debrid:  debridlink
[debridlink] 2025/01/15 07:48:54 Torrent: Free Guy 2021 2160p WEB-DL DDP5 1 Atmos DV MP4 x265-FLUX is not cached
[QBit] 2025/01/15 07:48:54 Error adding magnet: failed to process torrent: failed to process torrent
2025/01/15 07:48:54 Error checking availability: {"success":false,"error":"unknowR","error_description":"Endpoint not found."}
status code: 404
2025/01/15 07:48:55 Processing debrid:  torbox
[QBit] 2025/01/15 07:48:55 isSymlink: true
[torbox] 2025/01/15 07:48:55 Torrent Hash: C40D9A1E7415DCA3AB62BCC6228791BABFBE933C
[torbox] 2025/01/15 07:48:56 Torrent: Free Guy 2021 2160p WEB-DL DDP5 1 Atmos HDR HEVC-EVO mkv is not cached
[realdebrid] 2025/01/15 07:48:56 Torrent Hash: C40D9A1E7415DCA3AB62BCC6228791BABFBE933C
2025/01/15 07:48:56 Processing debrid:  realdebrid
2025/01/15 07:48:56 Error checking availability: {
	"error": "disabled_endpoint",
	"error_code": 37
}
status code: 403
2025/01/15 07:48:56 Processing debrid:  debridlink
[realdebrid] 2025/01/15 07:48:56 Torrent: Free Guy 2021 2160p WEB-DL DDP5 1 Atmos HDR HEVC-EVO mkv is not cached
[debridlink] 2025/01/15 07:48:56 Torrent Hash: C40D9A1E7415DCA3AB62BCC6228791BABFBE933C
[debridlink] 2025/01/15 07:48:56 Torrent: Free Guy 2021 2160p WEB-DL DDP5 1 Atmos HDR HEVC-EVO mkv is not cached
[QBit] 2025/01/15 07:48:56 Error adding magnet: failed to process torrent: failed to process torrent
2025/01/15 07:48:56 Error checking availability: {"success":false,"error":"unknowR","error_description":"Endpoint not found."}
status code: 404
[QBit] 2025/01/15 07:48:57 isSymlink: true
2025/01/15 07:48:57 Processing debrid:  torbox
[torbox] 2025/01/15 07:48:57 Torrent Hash: 67ABCEBCAFCBBF521A065944488660C8462B2B81
2025/01/15 07:48:58 Processing debrid:  realdebrid
[torbox] 2025/01/15 07:48:58 Torrent: Free Guy 2021 2160p WEB-DL DDP5 1 Atmos HEVC-EVO mkv is not cached
[realdebrid] 2025/01/15 07:48:58 Torrent Hash: 67ABCEBCAFCBBF521A065944488660C8462B2B81
2025/01/15 07:48:58 Error checking availability: {
	"error": "disabled_endpoint",
	"error_code": 37
}
status code: 403
2025/01/15 07:48:58 Processing debrid:  debridlink
[realdebrid] 2025/01/15 07:48:58 Torrent: Free Guy 2021 2160p WEB-DL DDP5 1 Atmos HEVC-EVO mkv is not cached
[debridlink] 2025/01/15 07:48:58 Torrent Hash: 67ABCEBCAFCBBF521A065944488660C8462B2B81
[debridlink] 2025/01/15 07:48:58 Torrent: Free Guy 2021 2160p WEB-DL DDP5 1 Atmos HEVC-EVO mkv is not cached
[QBit] 2025/01/15 07:48:58 Error adding magnet: failed to process torrent: failed to process torrent
2025/01/15 07:48:58 Error checking availability: {"success":false,"error":"unknowR","error_description":"Endpoint not found."}
status code: 404
[QBit] 2025/01/15 07:48:59 isSymlink: true
[torbox] 2025/01/15 07:48:59 Torrent Hash: 5462EAA2D9F1944B88DA1B13ADFB77E7756739D1
2025/01/15 07:48:59 Processing debrid:  torbox
[torbox] 2025/01/15 07:49:00 Torrent: Free Guy 2021 2160p 4K WEB x265 10bit AAC5 1-[YTS MX] mkv is cached(or downloading)
[torbox] 2025/01/15 07:49:02 Torrent: Free Guy 2021 2160p 4K WEB x265 10bit AAC5 1-[YTS MX] mkv submitted to torbox
2025/01/15 07:49:02 Torrent: Free Guy 2021 2160p 4K WEB x265 10bit AAC5 1-[YTS MX] mkv added with id: 804840
[torbox] 2025/01/15 07:49:03 Torrent: Free Guy 2021 2160p WEBRip downloaded
[QBit] 2025/01/15 07:49:03 Checking 1 files...`
